version: '3.7'

services:
  traefik-server:
    image: traefik:v2.10.1
    container_name: traefik-server
    hostname: traefik-server
    command:
      - "--api.debug=true"
      - "--api.insecure=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--providers.file.filename=/etc/traefik/dynamic/dynamic.yml"
      - "--configfile=/etc/traefik/traefik.toml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./proxy.crt:/etc/ssl/certs/proxy.crt
      - ./proxy.key:/etc/ssl/private/proxy.key
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic:/etc/traefik/dynamic
