[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]

[api]
  insecure = true

[providers]
  [providers.file]
  filename = "/etc/traefik/dynamic/dynamic1.yml"

[log]
  level = "DEBUG"

[tls.certificates]
  [tls.certificates.default]
    certFile = "/etc/ssl/certs/proxy.crt"
    keyFile = "/etc/ssl/private/proxy.key"
