[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[api]
  insecure = true

[providers]
  [providers.file]
  filename = "/etc/traefik/dynamic/dynamic.yml"

[log]
  level = "DEBUG"

[tls]
  [[tls.certificates]]
    certFile = "/etc/ssl/certs/proxy.crt"
    keyFile = "/etc/ssl/private/proxy.key"

[certificatesResolvers.selfsigned]
  [certificatesResolvers.selfsigned.acme]
    email = "henninb@gmail.com"
    caServer = ""
